// Auto-generated types from Puzzlet
// Do not edit this file directly

export interface MathIn { [key: string]: any }

export interface MathOut {
  /**
   * The math question or topic the student needs help with
   */
  userMessage: string;
}


export interface Test$Math2In {
  /**
   * The math question or topic the student needs help with
   */
  userMessage: string;
}


export interface Test$Math2Out {
  /**
   * The answer to the math question
   */
  answer: string;
}


export interface Math {
  input: MathIn;
  output: MathOut;
}

export interface Test$Math2 {
  input: Test$Math2In;
  output: Test$Math2Out;
}
