// Auto-generated types from Puzzlet
// Do not edit this file directly

interface MathIn { [key: string]: any }

interface MathOut { [key: string]: string }

interface Test$Math2In {
  /**
   * The math question or topic the student needs help with
   */
  userMessage: string;
}


interface Test$Math2Out {
  /**
   * The answer to the math question
   */
  answer: string;
}


interface Math {
  input: MathIn;
  output: MathOut;
}

interface Test$Math2 {
  input: Test$Math2In;
  output: Test$Math2Out;
}

export default interface PuzzletTypes {
  "math.prompt.mdx": Math,
  "test/math2.prompt.mdx": Test$Math2
}
